version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: nestjs
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    expose:
      - '5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
