@baseUrl = http://localhost:3000
@contentType = application/json

### Create Product
POST {{baseUrl}}/products HTTP/1.1
content-type: application/json

{
  "name": "rice"
}

### search Products
GET {{baseUrl}}/products HTTP/1.1

### FindOne
GET {{baseUrl}}/products/1 HTTP/1.1

### UPDATE 
PUT  {{baseUrl}}/products/1 HTTP/1.1
content-type: application/json

  {
  "id": "5e6e11f46864361d7f46d349",
  "name": "rice new"
}

### Delete one product
DELETE {{baseUrl}}/products/1 HTTP/1.1