@baseUrl = http://localhost:3000
@contentType = application/json

### Create Product
POST {{baseUrl}}/products HTTP/1.1
content-type: application/json

{
  "name": "Jadilson"
}

### List All Products
GET {{baseUrl}}/products HTTP/1.1

### FindOne
GET {{baseUrl}}/products/5e6c16450671e4393cac4024 HTTP/1.1