@baseUrl = http://localhost:3000
@contentType = application/json

### Create Product
POST {{baseUrl}}/products HTTP/1.1
content-type: application/json

{
  "name": "rice"
}

### search Products
GET {{baseUrl}}/products HTTP/1.1

### FindOne
GET {{baseUrl}}/products/1 HTTP/1.1

### UPDATE 
PUT  {{baseUrl}}/products/1 HTTP/1.1
content-type: application/json

  {
  "id": "5e6e11f46864361d7f46d349",
  "name": "rice new"
}

### Delete one product
DELETE {{baseUrl}}/products/1 HTTP/1.1


### Login
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
  "username": "john",
  "password": "changeme"
}

### profile
GET {{baseUrl}}/auth/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTU4NDQwOTY4NCwiZXhwIjoxNTg0NDA5NzQ0fQ.VKRrd5YzuFBHMPEjt1I0xV0NZ4lyot68jODuvrQF1AA

